import Head from 'next/head'
import MainArea from '../components/MainArea'
import Sidebar from '../components/Sidebar'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Button challenge</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/button.png" />
      </Head>
      <main>
        <Sidebar/>
        <MainArea/>
    </main>
    </div>
  )
}
